#!/usr/bin/env python3
"""Generate a versioned offline worker after `flutter build web` completes."""
import hashlib
import json
from pathlib import Path

root = Path('build/web')
files = sorted(p for p in root.rglob('*') if p.is_file() and p.name not in {
    'sw.js', 'flutter_service_worker.js', '.last_build_id'
} and p.suffix != '.map')
version = hashlib.sha256()
for path in files:
    version.update(str(path.relative_to(root)).encode())
    version.update(path.read_bytes())
assets = [str(p.relative_to(root)) for p in files]
worker = """// Generated by tool/build_web.py. Do not edit.
const CACHE = 'trio-__VERSION__';
const ASSETS = __ASSETS__;
const ROOT = new URL('./', self.location.href);
const urls = ASSETS.map(path => new URL(path, ROOT).href);
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(urls)));
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('trio-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== ROOT.origin || !url.pathname.startsWith(ROOT.pathname)) return;
  const relative = url.pathname.slice(ROOT.pathname.length);
  if (relative === 'scores' || relative === 'rooms' || relative.startsWith('rooms/')) return;
  // Cache app assets only. Score requests and room connections stay online.
  const asset = event.request.mode === 'navigate'
    ? new URL('index.html', ROOT).href : url.origin + url.pathname;
  if (!urls.includes(asset)) return;
  event.respondWith(caches.open(CACHE).then(async cache =>
    (await cache.match(asset)) || fetch(event.request)));
});
""".replace('__VERSION__', version.hexdigest()[:16]).replace('__ASSETS__', json.dumps(assets))
(root / 'sw.js').write_text(worker)
print(f'Offline cache: {len(assets)} assets, version {version.hexdigest()[:16]}')
