#!/usr/bin/env python3
"""Generate a versioned offline worker after `flutter build web` completes."""
import hashlib
import json
from pathlib import Path

root = Path('build/web')
# Flutter's worker unregisters and reloads every page it controls. Nothing
# should register it, and old cached bootstraps that try must get a 404.
(root / 'flutter_service_worker.js').unlink(missing_ok=True)
files = sorted(p for p in root.rglob('*') if p.is_file() and p.name not in {
    'sw.js', 'flutter_service_worker.js', '.last_build_id'
} and p.suffix != '.map')
version = hashlib.sha256(Path(__file__).read_bytes())
for path in files:
    version.update(str(path.relative_to(root)).encode())
    version.update(path.read_bytes())
assets = [str(p.relative_to(root)) for p in files]
worker = """// Generated by tool/build_web.py. Do not edit.
const CACHE = 'trio-__VERSION__';
const ASSETS = __ASSETS__;
const ROOT = new URL('./', self.location.href);
// Cache the canonical homepage: Cloudflare redirects /index.html to /.
const urls = ASSETS.map(path => new URL(path === 'index.html' ? './' : path, ROOT).href);
// Take over as soon as this version is cached, even with app windows open.
// That never reloads a page: open pages keep the code they already loaded,
// so runs are not interrupted, and they switch to this version on their next
// load. Waiting for every window to close kept installed apps outdated.
self.addEventListener('install', event => {
  // Bypass the HTTP cache, which could still hold the previous version.
  const requests = urls.map(url => new Request(url, {cache: 'reload'}));
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(requests)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('trio-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== ROOT.origin || !url.pathname.startsWith(ROOT.pathname)) return;
  const relative = url.pathname.slice(ROOT.pathname.length);
  if (relative === 'scores' || relative === 'rooms' || relative.startsWith('rooms/')) return;
  // Cache app assets only. Score requests and room connections stay online.
  const asset = event.request.mode === 'navigate'
    ? ROOT.href : url.origin + url.pathname;
  if (!urls.includes(asset)) return;
  event.respondWith(caches.open(CACHE).then(async cache =>
    (await cache.match(asset)) || fetch(event.request)));
});
""".replace('__VERSION__', version.hexdigest()[:16]).replace('__ASSETS__', json.dumps(assets))
(root / 'sw.js').write_text(worker)
print(f'Offline cache: {len(assets)} assets, version {version.hexdigest()[:16]}')
